### ISSUE TITLE
Parse consensus/descriptor from bytes or string

### ISSUE THREAD

**Issue by dmgawel** [NullHypothesis/zoossh#2]
For making Tor analysis I parse consensuses and descriptors directly from tar.xz archive (from Collector). It would be great to have a public function to parse a descriptor from raw string (or []bytes). Another way would be to support tar.xz as it is commonly used on Collector, but first option would be more general. Making a temp file for every consensus/desciptor is simply too slow.

(Great lib anyway!)

**Comment by NullHypothesis** [comment]
Thanks for the suggestion, Dawid!

In fact, there already is a function that takes as input a raw string and returns the descriptor: `ParseRawDescriptor(rawDescriptor string) (Fingerprint, GetDescriptor, error)`. Does that help?

> Making a temp file for every consensus/desciptor is simply too slow.

In my setup, I mirrored CollecTor, extracted all archives, and deleted the .tar.xz files. If you parse files repeatedly, this setup is actually quite fast. Also, when you parse .tar.xz files directly, you need to decompress them first, which takes a while.

**Comment by dmgawel** [comment]
Yes, that helps. I've used this function for parsing descriptors. What about consensuses?

**Comment by NullHypothesis** [comment]
There is currently no way to do that, I'm afraid, but I think it's a reasonable use case. I will try to add a function for that soon.

**Comment by NullHypothesis** [comment]
> I will try to add a function for that soon.

I'm afraid that won't happen anymore. However, I will leave this open and if anyone wants to write a patch, I would be happy to merge it.

**Comment by cmavromichalis** [comment]
I also needed this; pull request ready for review if you would like to merge:
https://github.com/NullHypothesis/zoossh/pull/7

**Comment by NullHypothesis** [comment]
> I also needed this; pull request ready for review if you would like to merge:
> #7

Looks like we're done with this issue, so I'm closing it.
